name: Generate EPUB

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install pandoc
      run: |
        sudo apt-get install -y pandoc

    - name: Generate EPUB
      run: |
        pandoc onlisp.org -f org -t epub -o on_lisp__advanced_techniques_for_common_lisp_-_paul_graham.epub

    - name: Upload EPUB
      uses: actions/upload-artifact@v2
      with:
        name: EPUB file
        path: on_lisp__advanced_techniques_for_common_lisp_-_paul_graham.epub
